name: starcastle_todoapp
description: "A Flutter project for Star Castle - To Do App (Kids Habit Tracker)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.3.10

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # UI & Animations
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  confetti: ^0.7.0

  # Localization (aktif kullanmasak da hazır)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Security
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0

  # Hive model generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
  hive_test: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    # Backgrounds
    - assets/backgrounds/castle/
    - assets/backgrounds/elements/

    # Icons
    - assets/icons/

    # Animations
    - assets/animations/
    - assets/animations/splash/

    # Albums
    - assets/albums/cars/
    - assets/albums/flowers/
    - assets/albums/jobs/
    - assets/albums/princess/
    - assets/albums/superheroes/

    # Stickers
    - assets/stickers/cars/
    - assets/stickers/flowers/
    - assets/stickers/jobs/
    - assets/stickers/princess/
    - assets/stickers/superheroes/

    # Illustrations (Empty states, rehber ekranlar)
    - assets/illustrations/
