// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXElYntaGjlOP_QnaSIWyz3VyoK2XLjZA',
    appId: '1:406665737995:web:bce029efbf29317d80d40e',
    messagingSenderId: '406665737995',
    projectId: 'starcastle-978e9',
    authDomain: 'starcastle-978e9.firebaseapp.com',
    storageBucket: 'starcastle-978e9.firebasestorage.app',
    measurementId: 'G-ZXD4DKPFJG',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZ1ZS1oZ1aGy71Oz-2vyPIxeTtxFy2zo',
    appId: '1:406665737995:android:f7e01d754c5f4ec580d40e',
    messagingSenderId: '406665737995',
    projectId: 'starcastle-978e9',
    storageBucket: 'starcastle-978e9.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIDjMUcwWdhzj5l0smLYPFrJ8-h7GtuE',
    appId: '1:406665737995:ios:7b0eb8269de2a04180d40e',
    messagingSenderId: '406665737995',
    projectId: 'starcastle-978e9',
    storageBucket: 'starcastle-978e9.firebasestorage.app',
    iosBundleId: 'com.starcastle.todoapp.starcastleTodoapp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIDjMUcwWdhzj5l0smLYPFrJ8-h7GtuE',
    appId: '1:406665737995:ios:7b0eb8269de2a04180d40e',
    messagingSenderId: '406665737995',
    projectId: 'starcastle-978e9',
    storageBucket: 'starcastle-978e9.firebasestorage.app',
    iosBundleId: 'com.starcastle.todoapp.starcastleTodoapp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXElYntaGjlOP_QnaSIWyz3VyoK2XLjZA',
    appId: '1:406665737995:web:8f1e23d8b6294e5880d40e',
    messagingSenderId: '406665737995',
    projectId: 'starcastle-978e9',
    authDomain: 'starcastle-978e9.firebaseapp.com',
    storageBucket: 'starcastle-978e9.firebasestorage.app',
    measurementId: 'G-S7VX9WGTNJ',
  );
}
